# Generated by Django 4.2.11 on 2024-05-30 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friendship", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FriendRequest",
            new_name="FollowRequest",
        ),
        migrations.AlterModelOptions(
            name="followrequest",
            options={"verbose_name": "Follow_Request"},
        ),
        migrations.AlterModelTable(
            name="followrequest",
            table="follow_request",
        ),
    ]
