# Generated by Django 4.2.11 on 2024-05-30 11:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0002_rename_friendrequest_followrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("not_accepted", "Not Accepted"),
                    ("declined", "Declined"),
                ],
                default="not_accepted",
                max_length=20,
            ),
        ),
    ]
