# Generated by Django 4.2.11 on 2024-05-29 09:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_date_of_birth_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, max_length=8, null=True, verbose_name="Date Of Birth"
            ),
        ),
    ]
